Initial
go-park-mail-ru/2024_2_GOATS pull request #3
Opened 2024-09-22 11:11 UTC by UnicoYal

База для монолита на хттп

2024-09-22 19:26 UTC, Starlexxx requested changes

2024-09-22 19:26 UTC, Starlexxx commented on config/config.go
> +type HTTPServer struct {
А че это в Listener не запихнуть

2024-09-22 19:26 UTC, Starlexxx commented on config/config_methods.go
Не принято в го называть так файлы и функции: чем короче, тем лучше назови файл `context.go`, а функции `WrapContext` и `FromContext` тогда у тебя будет в коде это выглядеть прилично. Создание конфига вынеси в основной `config.go`: где ты структуру объявил, там и должна быть функция, создающая объект.

2024-09-22 19:26 UTC, Starlexxx commented on config/config_methods.go
> +	"github.com/joho/godotenv"
Читать конфиг и брать из енвов переменные лучше через [viper](https://github.com/spf13/viper).

2024-09-22 19:26 UTC, Starlexxx commented on docker-compose.yml
> +version: '3.9'
deprecated

2024-09-22 19:26 UTC, Starlexxx commented on internal/app/api/implementation.go
> +type ServiceInterface interface {
для каких целей вам нужен этот интерфейс? Вы собираетесь делать несколько его реализаций? Зачем?

2024-09-22 19:26 UTC, Starlexxx commented on internal/app/app.go
> +	router := router.SetupRouter(ctx, apiLayer)
коллизия с названием пакета

2024-09-22 19:26 UTC, Starlexxx commented on internal/app/app.go
> +type App struct{}
зачем вам эта пустая структура, какой в ней смысл?

2024-09-22 19:26 UTC, Starlexxx commented on internal/app/router/router.go
> +func LoginHandler(ctx context.Context, api *api.Implementation, next http.Handler) http.Handler {
Обработчики выносить в отдельные пакеты

2024-09-22 19:26 UTC, Starlexxx commented on internal/app/service/service.go
> +type RepositoryInterface interface {
Почему этот интерфейс объявлен в сервисе

2024-09-22 19:26 UTC, Starlexxx commented on internal/db/db.go
> +func SetupDatabase(ctx context.Context) {
пускай эта функция будет возвращать коннекшн

2024-09-22 19:26 UTC, Starlexxx commented on internal/db/db.go
> +	ctxVals := config.GetConfigFromContext(ctx)
Хочу, чтобы тут был контекст с протуханием, чтобы вы не бесконечно ретраились.

2024-09-22 19:26 UTC, Starlexxx commented on internal/db/db.go
> +	defer DB.Close()
а если не получится закрыть коннекшн, где обработка ошибки?

2024-09-22 19:55 UTC, UnicoYal commented on internal/app/service/service.go
> +type RepositoryInterface interface {
Ну он же должен быть объявлен по месту использования. Тут он как раз используется

2024-09-23 10:03 UTC, Starlexxx commented on internal/app/api/implementation.go
> +type ServiceInterface interface {
окей, если хотите так делать, то оставляем

2024-09-23 10:21 UTC, Starlexxx commented on config/config.go
> +	return &Config{}
В этой функции у тебя структура конфига должна наполниться из ямлика, а врап контекст должен только обернуть объект конфига в контекст, он у тебя делает то, что не предполагается названием

2024-09-23 10:21 UTC, Starlexxx commented on config/context.go
> +	data, err := os.ReadFile(filename)
тебе не нужен os.ReadFile, пожалуйста, почитай, как работает viper в репозитории, который я кидал

2024-09-23 10:21 UTC, Starlexxx commented on internal/app/router/router.go
> +	router.Handle("/login", handler.Login(ctx, api, router)).Methods("POST")
Я бы на вашем месте объединил бы всю авторизацию в саброутер auth и вынес бы в отдельный пакет все что касается авторизации. Муви колекшнз я бы вытеснил в отдельный саброутр подборок, их же у вас много будет, а это главная, получается

2024-09-23 10:21 UTC, Starlexxx commented on internal/app/app.go
> +type App struct {
Если у вас App -- главная кор структура, то я бы в нее еще контекст засунул бы

2024-09-23 10:21 UTC, Starlexxx commented on internal/app/app.go
> +func setupViper() {
это все должно быть в конфиге в New()

2024-09-23 10:21 UTC, Starlexxx commented on internal/config/config.yml
> +  name: netflix
Я бы кста везде заменил бы уже нетфликс на ваше название

2024-09-23 20:19 UTC, Starlexxx commented on config/config.go
> +		Address:     viper.GetString("listener.address"),
повесь на поля структур теги ямловские, чтобы это все автоматом работало

2024-09-24 20:16 UTC, UnicoYal commented on internal/app/models/cookie/cookie.go
> +const cookieMaxAge = time.Hour * 24
В кфг

2024-09-24 20:17 UTC, UnicoYal commented on internal/app/models/models.go
> +package models
Почистить ненужные структуры

2024-09-24 20:17 UTC, UnicoYal commented on internal/app/repository/login.go
> +			return nil, &models.ErrorObj{
Вынести создание ErrorObj в пакет errors

2024-09-24 20:18 UTC, UnicoYal commented on internal/app/repository/register.go
> +		return nil, fmt.Errorf("error create user: %w", err)
Ошибки надо ErrorObj

2024-09-24 20:20 UTC, UnicoYal commented on internal/app/handlers/auth/handler.go
> +		w.Header().Set("Content-Type", "application/json")
В мидлварю

2024-09-27 11:17 UTC, Starlexxx reviewed
Жду правки и тесты

2024-09-27 11:17 UTC, Starlexxx commented on internal/app/repository/session.go
> +	defer cookieStore.RedisDB.Close()
обработка ошибки

2024-09-27 11:17 UTC, Starlexxx commented on internal/app/repository/session.go
> +		if err == sql.ErrNoRows {
писал выше

2024-09-27 11:17 UTC, Starlexxx commented on internal/app/repository/session.go
> +	err = r.Database.QueryRowContext(
Заменить на функцию, которую ты создашь

2024-09-27 11:17 UTC, Starlexxx commented on internal/app/service/register.go
> +	errVals "github.com/go-park-mail-ru/2024_2_GOATS/internal/app/errors"
по всему проекту прогони goimports

2024-09-27 11:17 UTC, Starlexxx commented on internal/config/config.yml
> +# postgres: local
артефакт

2024-09-27 11:17 UTC, Starlexxx commented on internal/db/schema/db.sql
> +  ('Оно', 2, 'Когда в городке Дерри, штат Мэн, начинают пропадать дети, несколько ребят сталкиваются со своими величайшими страхами и вынуждены помериться силами со злобным клоуном Пеннивайзом, чьи п
не относится к схеме, это сиды

2024-09-27 11:17 UTC, Starlexxx commented on internal/db/schema/db.sql
> +  CONSTRAINT valid_title CHECK ( LENGTH(title) >= 3 )
лично я против валидаций на уровне бд, у тебя есть приложение для этого

2024-09-27 11:17 UTC, Starlexxx commented on internal/db/schema/db.sql
> +  sex varchar CHECK(sex IN ('male', 'female', 'other', 'secret')),
расточительство

2024-09-27 11:17 UTC, Starlexxx commented on internal/db/schema/db.sql
> +  movie_type varchar CHECK(movie_type IN ('film', 'serial')),
расточительство

2024-09-28 15:25 UTC, Starlexxx reviewed
жду тесты

2024-09-28 15:25 UTC, Starlexxx commented on internal/app/handlers/auth.go
> +	cookieProcessor(a.ApiLayer.Ctx, w, authResp.Token)
ответ может быть нилом и токен тоже

2024-09-28 15:25 UTC, Starlexxx commented on internal/app/handlers/auth.go
> +		log.Errorf("failed to connect to Redis: %w", err)
%v, %w только в fmt

2024-09-28 15:25 UTC, Starlexxx commented on internal/app/repository/login.go
> +	user, err := user.FindByEmail(ctx, loginData.Email, r.Database)
коллизия

2024-09-28 15:25 UTC, Starlexxx commented on internal/app/repository/register.go
> +	user, err := user.Create(ctx, *registerData, r.Database)
коллизия

2024-09-28 15:25 UTC, Starlexxx commented on internal/app/repository/session.go
> +	user, err := user.FindById(ctx, userId, r.Database)
коллизия

2024-09-28 15:25 UTC, Starlexxx commented on internal/config/config.yml
> +postgres:
по хорошему постгрю и редис надо объеденить в databases

2024-09-28 15:25 UTC, Starlexxx commented on internal/db/db.go
> +			log.Errorf("Failed to connect to database. Error: %w. Retrying...", err)
%v тоже по всему проекту пройдись

2024-09-29 12:38 UTC, Starlexxx commented on config/config.go
> +type ConfigContextKey struct{}
вынести в файл контекста объявление должно быть там, где применение

2024-09-29 12:38 UTC, Starlexxx commented on internal/app/handlers/auth.go
> +			return
по отступам пройдись, не забывай пробел

2024-10-02 10:08 UTC, Starlexxx submitted a review, later dismissed

2024-10-02 11:14 UTC, merged